### ISSUE TITLE
SC-23 ⁃ 2.0: Docker build should also create a latest tag

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/capacity#141]
The docker build needs to create a latest tag and push that tag to dockerhub just like Control does.
Please see the below for Control's example:

https://github.com/supergiant/control/blob/master/docker_build.sh
https://github.com/supergiant/control/blob/master/docker_push.sh

**Comment by saheienko** [comment]
Fixed with https://github.com/supergiant/capacity/pull/146
